parameters:
#    you_food_service.example.class: YouFood\ServiceBundle\Example

services:
#    you_food_service.example:
#        class: %you_food_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
