<?php

namespace YouFood\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodCategoryRepository extends EntityRepository
{
}