<?php

namespace YouFood\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YouOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YouOrderRepository extends EntityRepository
{
}