parameters:
#    you_food_room.example.class: YouFood\RoomBundle\Example

services:
#    you_food_room.example:
#        class: %you_food_room.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
